server:
  port: 7070

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
#    hostname: service-provider
#  client:
#    service-url:
##      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@localhost:8761/eureka/,http://root:123@localhost:8762/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: service-provider