server:
  port: 7072

eureka:
  client:
    service-url:
      defaultZone: http://root:123@localhost:8761/eureka/,http://root:123@localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: service-provider
