server:
  port: 9091
  tomcat:
    max-threads: 10

eureka:
  client:
    service-url:
      defaultZone: http://root:123@localhost:8761/eureka/,http://root:123@localhost:8762/eureka/
    register-with-eureka: false
    registry-fetch-interval-seconds: 10


service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    listOfServers: http://localhost:7070,http://localhost:7071,http://localhost:7072

spring:
  application:
    name: service-feign-consumer
  redis:
    timeout: 10000
    host: localhost
    port: 16379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 5

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 512
    response:
      enabled: true
  httpclient:
    enabled: true

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000